[package]
name = "ecs-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
minijinja = "2.8.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.12"
